
language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

notifications:
  email: true

script: mvn clean verify  --quiet

after_success:
  - bash <(curl -s https://codecov.io/bash)
